### ISSUE TITLE
Multiple crashes on 1.21.1 with Alpha 2, all similar logs.

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#18]
11 crashes sometimes only an hour apart.
All reports look about the same:
```

Time: 2024-10-28 21:45:07
Description: Watching Server

java.lang.Error: Watchdog
	at java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@21.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@21.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	at knot//com.axalotl.async.ParallelProcessor.postEntityTick(ParallelProcessor.java:111)
	at knot//net.minecraft.class_1937.handler$zen000$async$postEntityPreBlockEntityTick(class_1937.java:2079)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at knot//net.minecraft.server.MinecraftServer$$Lambda/0x000000a8021d6000.run(Unknown Source)
	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@21.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@21.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@21.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@21.0.5/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	at knot//com.axalotl.async.ParallelProcessor.postEntityTick(ParallelProcessor.java:111)
	at knot//net.minecraft.class_1937.handler$zen000$async$postEntityPreBlockEntityTick(class_1937.java:2079)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at knot//net.minecraft.server.MinecraftServer$$Lambda/0x000000a8021d6000.run(Unknown Source)
Mixins in Stacktrace:
	net.minecraft.class_1937:
		me.jellysquid.mods.lithium.mixin.world.inline_height.WorldMixin (lithium.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.data_storage.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.WorldMixin (lithium.mixins.json)
		com.axalotl.async.mixin.world.WorldMixin (async.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WorldMixin (lithium.mixins.json)
		me.lucko.spark.fabric.mixin.WorldAccessor (spark.mixins.json)
		me.jellysquid.mods.lithium.mixin.minimal_nonvanilla.collisions.empty_space.WorldMixin (lithium.mixins.json)
		dev.architectury.mixin.fabric.MixinLevel (architectury.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin (lithium.mixins.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.fabric.mixins.json)
		de.dafuqs.head_in_the_clouds.mixin.WorldMixin (head_in_the_clouds.mixins.json)
		net.fabricmc.fabric.mixin.attachment.AttachmentTargetsMixin (fabric-data-attachment-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.block_entity_retrieval.WorldMixin (lithium.mixins.json)
		net.kyori.adventure.platform.fabric.impl.accessor.minecraft.world.level.LevelAccess (adventure-platform-fabric.accessor.mixins.json)
	net.minecraft.class_3218:
		me.jellysquid.mods.lithium.mixin.util.chunk_status_tracking.ServerWorldMixin (lithium.mixins.json)
		me.lucko.spark.fabric.mixin.ServerWorldAccessor (spark.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		xyz.nucleoid.fantasy.mixin.ServerWorldMixin (fantasy.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.cache_strongholds.ServerLevelMixin (modernfix-common.mixins.json)
		net.sssubtlety.leaves_us_in_peace.mixin.ServerWorldMixin (leaves_us_in_peace.mixins.json)
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		net.unknownuser.letitrain.mixins.ServerWorldMixin (letitrain.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.accessors.ServerWorldAccessor (lithium.mixins.json)
		com.natamus.collective.fabric.mixin.ServerLevelMixin (collective_fabric.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		ericthelemur.personalend.mixin.ServerWorldMixin (personal-end.mixins.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerWorldAccessor (lithium.mixins.json)
		com.axalotl.async.mixin.world.ServerWorldMixin (async.mixins.json)
		net.fabricmc.fabric.mixin.attachment.ServerWorldMixin (fabric-data-attachment-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.chunk_deadlock.ServerLevelMixin (modernfix-common.mixins.json)
	net.minecraft.server.MinecraftServer:
		org.embeddedt.modernfix.fabric.mixin.core.MinecraftServerMixin (modernfix-fabric.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftServerMixin (modernfix-common.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
		xyz.nucleoid.fantasy.mixin.MinecraftServerMixin (fantasy.mixins.json)
		net.kyori.adventure.platform.fabric.impl.mixin.minecraft.server.MinecraftServerMixin (adventure-platform-fabric.mixins.json)
		net.pcal.fastback.mod.fabric.mixins.ServerAccessors (fastback.mixins.json)
		net.litetex.sspb.mixin.MinecraftServerPWEMixin (sspb.mixins.json)
		com.axalotl.async.mixin.server.MinecraftServerMixin (async.mixins.json)
		org.embeddedt.modernfix.common.mixin.core.MinecraftServerMixin (modernfix-common.mixins.json)
		net.fabricmc.fabric.mixin.biome.modification.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftServerMixin (collective_fabric.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftServerMixin (balm.fabric.mixins.json)
		net.litetex.sspb.mixin.MinecraftServerFixParkNanosMixin (sspb.mixins.json)
		net.pcal.fastback.mod.fabric.mixins.MinecraftServerMixin (fastback.mixins.json)
		io.github.thecsdev.tcdcommons.mixin.events.MixinMinecraftServer (tcdcommons.mixin.events.json)
		net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (fabric-message-api-v1.mixins.json)
		com.frikinjay.letmedespawn.mixin.MinecraftServerMixin (letmedespawn.mixins.json)
		xyz.nucleoid.fantasy.mixin.MinecraftServerAccess (fantasy.mixins.json)
	net.minecraft.class_3176:
		dev.worldgen.lithostitched.mixin.server.DedicatedServerMixin (lithostitched.mixins.json)
		dev.architectury.mixin.fabric.MixinDedicatedServer (architectury.mixins.json)
		com.aizistral.nochatreports.common.mixins.server.MixinDedicatedServer (mixins/common/nochatreports.mixins.json)
		net.litetex.sspb.mixin.MinecraftDedicatedServerPWEMixin (sspb.mixins.json)
```
All logs:
[archive-2024-10-29T065107+0100.tar.gz](https://github.com/user-attachments/files/17552171/archive-2024-10-29T065107%2B0100.tar.gz)

**Comment by AxalotLDev** [comment]
Try use new Pre release 0.1.1-alpha.5

**Comment by RMEngelbrecht** [comment]
@AxalotLDev Updated as soon as I saw the new version, I put a new crash in #20
