### ISSUE TITLE
Exception ticking world on 1.21.1 Alpha 5

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#20]
Just had a ticking exception on Alpha 5(4?) on 1.21.1.

A ton of Lithium mixins in the trace though, so I am wondering if I should just remove Lithium for now.

### Immediate crash in log:
```
13:45:58] [Server thread/ERROR]: Negative index in crash report handler (0/7)
[13:45:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
        at knot/net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

### Stacktrace:
```Log
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1693)
Mixins in Stacktrace:
	net.minecraft.class_3218:
		me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerWorldAccessor (lithium.mixins.json)
		com.natamus.collective.fabric.mixin.ServerLevelMixin (collective_fabric.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		net.unknownuser.letitrain.mixins.ServerWorldMixin (letitrain.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.chunk_status_tracking.ServerWorldMixin (lithium.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		me.lucko.spark.fabric.mixin.ServerWorldAccessor (spark.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.accessors.ServerWorldAccessor (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.cache_strongholds.ServerLevelMixin (modernfix-common.mixins.json)
		xyz.nucleoid.fantasy.mixin.ServerWorldMixin (fantasy.mixins.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
		net.fabricmc.fabric.mixin.attachment.ServerWorldMixin (fabric-data-attachment-api-v1.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.chunk_deadlock.ServerLevelMixin (modernfix-common.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		net.sssubtlety.leaves_us_in_peace.mixin.ServerWorldMixin (leaves_us_in_peace.mixins.json)
		ericthelemur.personalend.mixin.ServerWorldMixin (personal-end.mixins.json)
		com.axalotl.async.mixin.world.ServerWorldMixin (async.mixins.json)
```

### Additional errors.
Before this all, there was the following error and a lot of spam in the console. The error got spammed another 65 times after this and before the crash happened.
```
[13:33:19] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
        at knot/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1301) ~[fastutil-8.5.12.jar:?]
        at knot/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:255) ~[fastutil-8.5.12.jar:?]
        at knot/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:455) ~[fastutil-8.5.12.jar:?]
        at knot/net.minecraft.class_3204.method_14050(class_3204.java:199) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3204.method_14042(class_3204.java:151) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3204$class_3948.method_17667(class_3204.java:426) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3215.method_19492(class_3215.java:263) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:852) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:9125) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[13:33:19] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:33:19] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:33:19] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:35:23] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:35:23] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:35:23] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:38:08] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:42:45] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:42:45] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:42:45] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[13:42:45] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.lang.ArrayIndexOutOfBoundsException: null
[etc. etc.]
```

**Comment by AxalotLDev** [comment]
What version of lithium? Send me full log.

**Comment by RMEngelbrecht** [comment]
> What version of lithium? Send me full log.

Lithium 0.13.1
Here is the full logs:
[2024-10-29-3.log](https://github.com/user-attachments/files/17557474/2024-10-29-3.log)
[crash-2024-10-29_13.45.58-server.txt](https://github.com/user-attachments/files/17557476/crash-2024-10-29_13.45.58-server.txt)

**Comment by AxalotLDev** [comment]
Try to reproduce the error with this mod: https://modrinth.com/mod/stackdeobf

**Comment by RMEngelbrecht** [comment]
We just had this happen with the stackdeobf mod enabled, but it doesn't show any mixins so not sure if relevant.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-10-29 16:41:16
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.world.ChunkTicket.isExpired(long)" because "$$4" is null
	at knot//MC//net.minecraft.server.world.ChunkTicketManager.purge(ChunkTicketManager.java:88)
	at knot//MC//net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:305)
	at knot//MC//net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:350)
	at knot//net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1021)
	at knot//MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:299)
	at knot//net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//MC//net.minecraft.server.world.ChunkTicketManager.purge(ChunkTicketManager.java:88)
	at knot//MC//net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:305)
Mixins in Stacktrace: None found
```

**Comment by AxalotLDev** [comment]
Ok, try new version

**Comment by RMEngelbrecht** [comment]
@AxalotLDev I have 4 new crashes on 0.1.2 Alpha 1, Minecraft 1.21.1
Logs:
[crash-2024-10-31_23.08.20-server.txt](https://github.com/user-attachments/files/17596848/crash-2024-10-31_23.08.20-server.txt)
[crash-2024-10-31_23.22.21-server.txt](https://github.com/user-attachments/files/17596849/crash-2024-10-31_23.22.21-server.txt)
[crash-2024-10-31_23.34.16-server.txt](https://github.com/user-attachments/files/17596850/crash-2024-10-31_23.34.16-server.txt)
[crash-2024-10-31_23.40.50-server.txt](https://github.com/user-attachments/files/17596851/crash-2024-10-31_23.40.50-server.txt)

**Comment by AxalotLDev** [comment]
> @AxalotLDev I have 4 new crashes on 0.1.2 Alpha 1, Minecraft 1.21.1 Logs: [crash-2024-10-31_23.08.20-server.txt](https://github.com/user-attachments/files/17596848/crash-2024-10-31_23.08.20-server.txt) [crash-2024-10-31_23.22.21-server.txt](https://github.com/user-attachments/files/17596849/crash-2024-10-31_23.22.21-server.txt) [crash-2024-10-31_23.34.16-server.txt](https://github.com/user-attachments/files/17596850/crash-2024-10-31_23.34.16-server.txt) [crash-2024-10-31_23.40.50-server.txt](https://github.com/user-attachments/files/17596851/crash-2024-10-31_23.40.50-server.txt)

Try increasing the max-tick-time value in the server.properties file

**Comment by AxalotLDev** [comment]
try https://modrinth.com/mod/async/version/0.1.2+alpha.2-1.21.1

**Comment by FurryMileon** [comment]
It should be fixed in the new version.
