### ISSUE TITLE
Sepals and other incompatibilities

### ISSUE THREAD

**Issue by xbxct** [AxalotLDev/Async#28]
-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'async' at ''!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1234)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:175)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'async' at ''!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1232)
	... 3 more
Caused by: java.lang.IllegalAccessError: class it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator cannot access its abstract superclass it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator (it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @43d7741f; it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:321)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:351)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:254)
	at org.quiltmc.loader.impl.launch.knot.Knot.loadIntoTarget(Knot.java:394)
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.loadIntoTarget(FabricLauncherBase.java:72)
	at com.axalotl.async.parallelised.fastutil.sync.SyncFuTransformer.onPreLaunch(SyncFuTransformer.java:21)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 6 more

**Comment by suerion** [comment]
Looks more like an Issue on Quilt loading, but you could add the full log,

**Comment by FurryMileon** [comment]
> -- Crash --
> 
> org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'async' at ''! at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1234) at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:175) at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78) at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'async' at ''! at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1232) ... 3 more Caused by: java.lang.IllegalAccessError: class it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator cannot access its abstract superclass it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator (it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @43d7741f; it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator is in unnamed module of loader 'app') at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:321) at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:351) at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:254) at org.quiltmc.loader.impl.launch.knot.Knot.loadIntoTarget(Knot.java:394) at net.fabricmc.loader.impl.launch.FabricLauncherBase.loadIntoTarget(FabricLauncherBase.java:72) at com.axalotl.async.parallelised.fastutil.sync.SyncFuTransformer.onPreLaunch(SyncFuTransformer.java:21) at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ... 6 more

Unfortunately, Sepals is not compatible with async because a lot of code would need to be rewritten for Sepals to work. We'll consider its compatibility later, and most likely that will be after the mod is fully stable on the new version.

**Comment by xboct02** [comment]
> Больше похоже на проблему при загрузке Quilt, но вы можете добавить полный журнал,

There is a restriction on the words

**Comment by xboct02** [comment]
> Больше похоже на проблему при загрузке Quilt, но вы можете добавить полный журнал,

Существует ограничение на количество слов

**Comment by xbxct** [comment]
> Больше похоже на проблему при загрузке Quilt, но вы можете добавить полный журнал,

There is a character limit

**Comment by Tiri2** [comment]
> > Больше похоже на проблему при загрузке Quilt, но вы можете добавить полный журнал,
> 
> There is a character limit

Use a service like pasebin btw

**Comment by AxalotLDev** [comment]
Sepals is now support, but is very broken

**Comment by AxalotLDev** [comment]
UPD: Not work, but we decided not to add support to avoid performance issues
