### ISSUE TITLE
Crash due to Fabric Lifecycle Events (v1), incompatibility with Jade & Presence Footsteps

### ISSUE THREAD

**Issue by iguanacucumber** [AxalotLDev/Async#35]
Hi i updated to 0.1.5 beta, and when i join a world, the game crashes when i have Jade or Presence Footsteps installed. This happens only on 0.1.5, works well on 0.1.4

Here's the logs: [mclo.gs/7VHBxcM](https://mclo.gs/7VHBxcM)

**Comment by FurryMileon** [comment]
> Hi i updated to 0.1.5 beta, and when i join a world, the game crashes when i have Jade or Presence Footsteps installed. This happens only on 0.1.5, works well on 0.1.4
> 
> Here's the logs: [mclo.gs/7VHBxcM](https://mclo.gs/7VHBxcM)

Hi! I carefully reviewed your log and didn't find anything pointing to an issue with the Async mod. It seems like other mods are conflicting. If you remove Async, will the error remain or disappear?

**Comment by iguanacucumber** [comment]
Async 0.1.5 conflicts with mods that heavly really on Fabric Lifecycle Events (v1) api such as Jade or Presence Footsteps. as i said this does not happen with priour versions of this mod or if i remove the mod:
```
[19:55:19] [Render thread/ERROR]: Error loading plugin at snownee.jade.addon.core.CorePlugin
java.lang.UnsupportedOperationException: null
	at knot/com.google.common.collect.ImmutableMultimap.put(ImmutableMultimap.java:436) ~[guava-32.1.2-jre.jar:?]
	at knot/snownee.jade.impl.lookup.HierarchyLookup.register(HierarchyLookup.java:48) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/snownee.jade.impl.WailaClientRegistration.registerBlockComponent(WailaClientRegistration.java:145) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/snownee.jade.impl.ClientRegistrationSession.lambda$end$1(ClientRegistrationSession.java:219) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at knot/snownee.jade.impl.ClientRegistrationSession.end(ClientRegistrationSession.java:219) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/snownee.jade.impl.WailaClientRegistration.endSession(WailaClientRegistration.java:565) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/snownee.jade.util.CommonProxy.lambda$loadComplete$5(CommonProxy.java:417) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at knot/snownee.jade.util.CommonProxy.loadComplete(CommonProxy.java:385) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/snownee.jade.util.ClientProxy.lambda$onInitializeClient$1(ClientProxy.java:252) ~[Jade-1.21-Fabric-15.1.5.jar:?]
	at knot/net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1 6c1df360d1-c0b4d6e7c3bfc603.jar:?]
```
Here's what's really important:
> at knot/***net.fabricmc.fabric.api.client.event.lifecycle.v1***.ClientLifecycleEvents.[...]

My only guess would be that Async 0.1.5 changed the behaviour of something in `net.fabricmc.fabric.api.client.event.lifecycle.v1`

**Comment by VindSole** [comment]
I'm completely unable to launch with 0.1.5 alpha 2, it crashes even when it's the only mod present, alpha 1 works fine.

**Comment by iguanacucumber** [comment]
seems to be fixed in the latest release
