### ISSUE TITLE
Incompatable with vanish

### ISSUE THREAD

**Issue by Grandev-0** [AxalotLDev/Async#37]
Any command typed out while in [vanish](https://modrinth.com/mod/vanish) will kick the client from the game with this error: Internal Exception: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3222.method_64475(int)' And these are the only logs related to it:
`[18:20:56] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@b05be42[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4633926e[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda/0x0000021484d15788@6c81a37e]] rejected from java.util.concurrent.ThreadPoolExecutor@e78de2e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 20011]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[?:?]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:785) ~[?:?]
	at knot/com.replaymod.recording.packet.PacketListener.save(PacketListener.java:205) ~[replaymod-1.21-2.6.19.jar:?]
	at knot/com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:193) ~[replaymod-1.21-2.6.19.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1240) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[18:20:56] [Render thread/INFO]: [voicechat] Clearing audio channels
[18:20:56] [Render thread/INFO]: [voicechat] Stopping microphone thread
[18:20:56] [Render thread/INFO]: [voicechat] Disconnecting voicechat
[18:20:56] [Render thread/INFO]: Stopping worker threads
[18:20:56] [Render thread/WARN]: Client disconnected with reason: Internal Exception: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3222.method_64475(int)'`

**Comment by AxalotLDev** [comment]
Can you provide a full log and write how you reproduced the error? Check if it is Async?

**Comment by wicivo** [comment]
I haven't encountered this problem even though I use vanish

**Comment by Grandev-0** [comment]
> Can you provide a full log and write how you reproduced the error? Check if it is Async?

Nevermind I just jumped to conclusions it was just [this](https://modrinth.com/mod/pandaantispam) mod that was causing it sorry for wasting your time.
