### ISSUE TITLE
[Compatibility] Compatible changes from Sepals

### ISSUE THREAD

**Issue by cao-awa** [AxalotLDev/Async#38]
Hi, sorry to bother, i am the author and developer of Sepals, i seen a issue report that says Async don't work with Sepals.

I've tested on Minecraft 1.21.4 recently, only 3 mods (Sepals, Async, Fabric-API), the result shown the compatible problems is from async access to the hash map when Sepals caching entities.

Then i try to detect Async loads and adapt to change map type to ConcurrentHashMap, that work.

This way make Async no more to throw exceptions, and seemingly doesn't causing too much performance burden.

I tested 2400 villager entities cramming, MSPT is lower than only Async or Sepals installed when server installed simultaneously Async and Sepals.

I've [commit](https://github.com/cao-awa/Sepals/commit/be22b441b7f0a9f13875769d2e5e408c2d4c41d5)ted and [build](https://github.com/cao-awa/Sepals/actions/runs/12488966321), please try this build, looking forward to cooperation, thanks!

**Comment by AxalotLDev** [comment]
Hi, we tested the mod and we have a couple of comments. When running and testing, we received the error below. And after fixing this error on our side, we felt a noticeable decrease in performance. Most likely, it is on our side, but without it, your mod does not work. 

Here is a rough comparison of performance with 6200 villagers:
async with fix sepals but without sepals itself 48 mspt
async with fix sepals and with sepals itself 55 mspt
async without fix and without sepals 34 mspt

Sepals error without fix:
```
[19:18:34] [Async-Tick-Pool-Thread-7/ERROR]: Error ticking entity translation{key='entity.minecraft.villager', args=[]} asynchronously, switching to synchronous processing
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 513
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
 at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
 at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
 at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) [?:?]
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489) [?:?]
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071) [?:?]
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033) [?:?]
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 513
 at knot/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.rehash(Object2ObjectOpenHashMap.java:1286) ~[fastutil-8.5.15.jar:?]
 at knot/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.insert(Object2ObjectOpenHashMap.java:251) ~[fastutil-8.5.15.jar:?]
 at knot/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.put(Object2ObjectOpenHashMap.java:259) ~[fastutil-8.5.15.jar:?]
 at knot//MC/net.minecraft.world.World.sepals$cache(World.java:10586) ~[server-intermediary.jar:?]
 at knot/com.github.cao.awa.sepals.item.BoxedEntitiesCache.cache(BoxedEntitiesCache.java:12) ~[Sepals-fabric-1.0.10.jar:?]
 at knot//MC/net.minecraft.world.World.handler$cdd000$sepals$cacheOtherEntities(World.java:10652) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.world.World.getOtherEntities(World.java:693) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.LivingEntity.handler$cck000$sepals$sepalsForceCramming(LivingEntity.java:11420) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.LivingEntity.tickCramming(LivingEntity.java) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:2952) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:575) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity.java:129) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2606) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:366) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.entity.passive.VillagerEntity.tick(VillagerEntity.java:319) ~[server-intermediary.jar:?]
 at knot//MC/net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:762) ~[server-intermediary.jar:?]
 at knot/com.axalotl.async.ParallelProcessor.performAsyncEntityTick(ParallelProcessor.java:112) ~[async-0.1.5+alpha.8-1.21.4%20(1st%20copy).jar:?]
 at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:69) ~[async-0.1.5+alpha.8-1.21.4%20(1st%20copy).jar:?]
 at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
 ... 6 more
 ```

**Comment by AxalotLDev** [comment]
[async.zip](https://github.com/user-attachments/files/18246795/async.zip)
Fix for testing

**Comment by cao-awa** [comment]
Hum... this not same result as mine, i used [spark](https://modrinth.com/mod/spark) mod to profile, here is my profiler result:
[Sepals(newerest github action build)+Async(async-0.1.5+alpha.7)](https://spark.lucko.me/qeuOXvuTlA) 
[Sepals(newerest github action build)+Async(async-0.1.5+alpha.8)](https://spark.lucko.me/bolOdOzPNB) 
[Async(async-0.1.5+alpha.8)](https://spark.lucko.me/Jz9QgBhFjO) 
[Sepals(newerest github action build)](https://spark.lucko.me/Z6XlX5i064)

All my platform and hardware configuration are record in profiler result, test entities is 2000 villagers.

That shown missing either will result in a slower ticking, even the graph on F3+2 frame also same here, is my got wrong async configurations or something? 

Unfortunately, spark cannot profiler the threads that not main thread, i cannot find what potential problems could we solve, may you do this profile or use something profiler tool like jprofiler for me? these two result (your result and mine result now) shown seem the behavoirs got different on different hardware platform?

**Comment by cao-awa** [comment]
And [vanilla baseline](https://spark.lucko.me/XXwBKlFjD4) here.

**Comment by FurryMileon** [comment]
> Hum... this not same result as mine, i used [spark](https://modrinth.com/mod/spark) mod to profile, here is my profiler result: [Sepals(newerest github action build)+Async(async-0.1.5+alpha.7)](https://spark.lucko.me/qeuOXvuTlA) [Sepals(newerest github action build)+Async(async-0.1.5+alpha.8)](https://spark.lucko.me/bolOdOzPNB) [Async(async-0.1.5+alpha.8)](https://spark.lucko.me/Jz9QgBhFjO) [Sepals(newerest github action build)](https://spark.lucko.me/Z6XlX5i064)
> 
> All my platform and hardware configuration are record in profiler result, test entities is 2000 villagers.
> 
> That shown missing either will result in a slower ticking, even the graph on F3+2 frame also same here, is my got wrong async configurations or something?
> 
> Unfortunately, spark cannot profiler the threads that not main thread, i cannot find what potential problems could we solve, may you do this profile or use something profiler tool like jprofiler for me? these two result (your result and mine result now) shown seem the behavoirs got different on different hardware platform?

I wanted to clarify about Sepals. While it optimizes ticks and slightly improves performance, it causes errors (example: https://youtu.be/brqjqUjtyAw). When we fix this error on our side, the MSPT becomes lower than without the Sepals fix.

**Comment by cao-awa** [comment]
> it causes errors (example: https://youtu.be/brqjqUjtyAw)

Alright, that my bad, the latest Sepals in modrinth is behind some changes of GitHub, i've upload the release to modrinth now.

Before this, I was testing using the artifact automatically build from GitHub.

Hope this works as expected.

**Comment by AxalotLDev** [comment]
Ok, we have enabled sepals in the configuration, but we will not add a bug fix for now because it reduces performance

**Comment by cao-awa** [comment]
So good! then choice up to users by configurations, this problem are solved. might i will continue try do more improve with async, we could close this issue now, thanks again!
