### ISSUE TITLE
Crash after leaving the end

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#5]
As title says, server crashed after a player left the end.

Stacktrace as follows:
```
java.lang.Error: Watchdog
	at java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
	at java.base@21.0.4/java.util.concurrent.Phaser$QNode.block(Phaser.java:1133)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@21.0.4/java.util.concurrent.Phaser.internalAwaitAdvance(Phaser.java:1063)
	at java.base@21.0.4/java.util.concurrent.Phaser.arriveAndAwaitAdvance(Phaser.java:685)
	at knot//com.axalotl.async.ParallelProcessor.postEntityTick(ParallelProcessor.java:143)
	at knot//net.minecraft.class_1937.handler$zcc000$async$postEntityPreBlockEntityTick(class_1937.java:1573)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at knot//net.minecraft.server.MinecraftServer$$Lambda/0x00000090021fe240.run(Unknown Source)
	at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
	at java.base@21.0.4/java.util.concurrent.Phaser$QNode.block(Phaser.java:1133)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@21.0.4/java.util.concurrent.Phaser.internalAwaitAdvance(Phaser.java:1063)
	at java.base@21.0.4/java.util.concurrent.Phaser.arriveAndAwaitAdvance(Phaser.java:685)
	at knot//com.axalotl.async.ParallelProcessor.postEntityTick(ParallelProcessor.java:143)
	at knot//net.minecraft.class_1937.handler$zcc000$async$postEntityPreBlockEntityTick(class_1937.java:1573)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at knot//net.minecraft.server.MinecraftServer$$Lambda/0x00000090021fe240.run(Unknown Source)
Mixins in Stacktrace:
	net.minecraft.class_1937:
		net.kyori.adventure.platform.fabric.impl.accessor.minecraft.world.level.LevelAccess (adventure-platform-fabric.accessor.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
		com.ishland.c2me.notickvd.mixin.MixinWorld (c2me-notickvd.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinWorld (c2me-opts-scheduling.mixins.json)
		net.fabricmc.fabric.mixin.attachment.AttachmentTargetsMixin (fabric-data-attachment-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_height.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.block_entity_retrieval.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin (lithium.mixins.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.fabric.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.data_storage.WorldMixin (lithium.mixins.json)
		de.dafuqs.head_in_the_clouds.mixin.WorldMixin (head_in_the_clouds.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		com.axalotl.async.mixin.WorldMixin (async.mixins.json)
		me.jellysquid.mods.lithium.mixin.minimal_nonvanilla.collisions.empty_space.WorldMixin (lithium.mixins.json)
		me.lucko.spark.fabric.mixin.WorldAccessor (spark.mixins.json)
	net.minecraft.class_3218:
		net.fabricmc.fabric.mixin.attachment.ServerWorldMixin (fabric-data-attachment-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		net.unknownuser.letitrain.mixins.ServerWorldMixin (letitrain.mixins.json)
		me.lucko.spark.fabric.mixin.ServerWorldAccessor (spark.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.chunk_status_tracking.ServerWorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
		xyz.nucleoid.fantasy.mixin.ServerWorldMixin (fantasy.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.shutdown.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.accessors.ServerWorldAccessor (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		ericthelemur.personalend.mixin.ServerWorldMixin (personal-end.mixins.json)
		com.natamus.collective.fabric.mixin.ServerLevelMixin (collective_fabric.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		com.axalotl.async.mixin.ServerWorldMixin (async.mixins.json)
		net.sssubtlety.leaves_us_in_peace.mixin.ServerWorldMixin (leaves_us_in_peace.mixins.json)
	net.minecraft.server.MinecraftServer:
		org.embeddedt.modernfix.fabric.mixin.core.MinecraftServerMixin (modernfix-fabric.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (fabric-message-api-v1.mixins.json)
		xyz.nucleoid.fantasy.mixin.MinecraftServerMixin (fantasy.mixins.json)
		net.litetex.sspb.mixin.MinecraftServerFixParkNanosMixin (sspb.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.shutdown.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		xyz.nucleoid.fantasy.mixin.MinecraftServerAccess (fantasy.mixins.json)
		com.frikinjay.letmedespawn.mixin.MinecraftServerMixin (letmedespawn.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
		io.github.thecsdev.tcdcommons.mixin.events.MixinMinecraftServer (tcdcommons.mixin.events.json)
		net.blay09.mods.balm.mixin.MinecraftServerMixin (balm.fabric.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftServerMixin (modernfix-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.core.MinecraftServerMixin (modernfix-common.mixins.json)
		net.pcal.fastback.mod.fabric.mixins.MinecraftServerMixin (fastback.mixins.json)
		com.axalotl.async.mixin.MinecraftServerMixin (async.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.idle_tasks.autosave.enhanced_autosave.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		net.pcal.fastback.mod.fabric.mixins.ServerAccessors (fastback.mixins.json)
		com.ishland.c2me.rewrites.chunksystem.mixin.MixinMinecraftServer (c2me-rewrites-chunk-system.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftServerMixin (collective_fabric.mixins.json)
		net.litetex.sspb.mixin.MinecraftServerPWEMixin (sspb.mixins.json)
		com.ishland.c2me.fixes.general.threading_issues.mixin.asynccatchers.MixinMinecraftServer (c2me-fixes-general-threading-issues.mixins.json)
		net.fabricmc.fabric.mixin.biome.modification.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		net.kyori.adventure.platform.fabric.impl.mixin.minecraft.server.MinecraftServerMixin (adventure-platform-fabric.mixins.json)
	net.minecraft.class_3176:
		com.aizistral.nochatreports.common.mixins.server.MixinDedicatedServer (mixins/common/nochatreports.mixins.json)
		dev.worldgen.lithostitched.mixin.server.DedicatedServerMixin (lithostitched.mixins.json)
		com.ishland.c2me.base.mixin.util.log4j2shutdownhookisnomore.MixinMinecraftDedicatedServer (c2me-base.mixins.json)
		net.litetex.sspb.mixin.MinecraftDedicatedServerPWEMixin (sspb.mixins.json)
```

**Comment by AxalotLDev** [comment]
Try use new Pre-release

**Comment by RMEngelbrecht** [comment]
Fixed again! Thank you for your hard work!
