### ISSUE TITLE
Single chunk with one or two zombie (villagers) crash

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#8]
My server had about a dozen crashes earlier today. Due to timezones I couldn't be there when it happened so I have no clue what caused is sadly. 

I'm not sure if it's helpful, but I'd figure I should just upload all the crashes here for you to look at:
[archive-2024-10-18.tar.gz](https://github.com/user-attachments/files/17428689/archive-2024-10-18.tar.gz)

Hopefully this helps with further development!

**Comment by wicivo** [comment]
> My server had about a dozen crashes earlier today. Due to timezones I couldn't be there when it happened so I have no clue what caused is sadly.
> 
> I'm not sure if it's helpful, but I'd figure I should just upload all the crashes here for you to look at: [archive-2024-10-18.tar.gz](https://github.com/user-attachments/files/17428689/archive-2024-10-18.tar.gz)
> 
> Hopefully this helps with further development!

I saw c2me in there, it's not compatible with Async.

**Comment by wicivo** [comment]
I wouldn't recommend installing Async on a server, it's a pretty experimental mod

**Comment by RMEngelbrecht** [comment]
@wicivo I'm completely aware of that! It's a super small server with a group of friends that have max 5 people online at any given time. Due to the CPU in the server it was running incredibly slow with a massive load in Entity Ticks, Async singlehandedly made the server playable.

Because of this I want this mod to do well, and I'm more than happy to have my low stakes server crash every now and then to help development. I make regular backups to make sure there is no data loss. Axalotl already fixed multiple Lithium crashes we ran into. Normally I have more accurate data though, which is why I'm not completely sure this is helpful.

To your c2me comment: if that is the culprit in this case then this issue can just be closed, however this is a c2me built that has async-incompatible mixins removed.

**Comment by AxalotLDev** [comment]
c2me is not officially compatible with async, but it may work if you change something. We are currently looking for ways to solve the compatibility issue.

**Comment by RMEngelbrecht** [comment]
Okay! Yeah I am using the modified version you posted in another issue earlier. But if it happens again I will outright remove it. Looking forward to the compatibility but take your time!

**Comment by RMEngelbrecht** [comment]
Update: I identified the issue to be with 1-2 specific chunks. What wasn't visible in the crash logs, but is visible in the server log itself was that there were a couple of Async errors thrown around a zombie (villager) specifically.

**HOWEVER, this was fixed by removing c2me, and thus I'd imagine this is just part of the compatibility with c2me project rather than an important bugfix.**

<details><summary>Error from log:</summary>
<p>
<pre>
  <code>
[Async-Tick-Pool-Thread-65/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (320.5, 43.0, -922.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-60/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (313.5, 65.0, -895.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19500(class_3218.java:1335) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_19053(class_1368.java:69) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_5535.method_31543(class_5535.java:102) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_5534.method_31530(class_5534.java:21) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:68) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-67/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie_villager', args=[]} at (372.5, 35.0, -805.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1641.method_5773(class_1641.java:156) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-68/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (380.5, 45.0, -811.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-66/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (439.5, 34.0, -909.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-64/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (457.5, 63.0, -910.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19500(class_3218.java:1335) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_19053(class_1368.java:69) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_5535.method_31543(class_5535.java:102) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_5534.method_31530(class_5534.java:21) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:68) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-69/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (455.5, -20.0, -867.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[12:02:31] [Async-Tick-Pool-Thread-63/ERROR]: Exception ticking Entity translation{key='entity.minecraft.zombie', args=[]} at (298.5, 43.0, -898.5)
java.util.NoSuchElementException: null
	at java.base/java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:1859) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:396) ~[?:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.firstLong(ConcurrentLongLinkedOpenHashSet.java:112) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/com.axalotl.async.parallelised.fastutil.ConcurrentLongLinkedOpenHashSet.removeFirstLong(ConcurrentLongLinkedOpenHashSet.java:152) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at knot/net.minecraft.class_8257.method_50019(class_8257.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3554.method_15492(class_3554.java:156) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153$class_4154.method_19134(class_4153.java:295) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4153.method_19118(class_4153.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19498(class_3218.java:1350) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_19497(class_3218.java:1346) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1368.method_6264(class_1368.java:64) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4135.method_6264(class_4135.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1355.method_6275(class_1355.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_6007(class_1642.java:266) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1642.method_5773(class_1642.java:238) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:132) ~[async-0.1.0+rc7-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
    </code>
  </pre>
</p>
</details>

**Comment by FurryMileon** [comment]
> Update: I identified the issue to be with 1-2 specific chunks. What wasn't visible in the crash logs, but is visible in the server log itself was that there were a couple of Async errors thrown around a zombie (villager) specifically.
> 
> **HOWEVER, this was fixed by removing c2me, and thus I'd imagine this is just part of the compatibility with c2me project rather than an important bugfix.**
> 
> Error from log:

Is this the latest version of the async mod?

**Comment by RMEngelbrecht** [comment]
> > Update: I identified the issue to be with 1-2 specific chunks. What wasn't visible in the crash logs, but is visible in the server log itself was that there were a couple of Async errors thrown around a zombie (villager) specifically.
> > **HOWEVER, this was fixed by removing c2me, and thus I'd imagine this is just part of the compatibility with c2me project rather than an important bugfix.**
> > Error from log:
> 
> Is this the latest version of the async mod?

Yes, this is rc7. And this exact crash just happened again without c2me

**Comment by AxalotLDev** [comment]
Try new version, this fix for c2me

**Comment by RMEngelbrecht** [comment]
I think we can close this one too.
When this popped up I killed the entities in question, but if it ever happens again I will open a new issue (but I have good hope it is solved now!)
